service: test

plugins:
    - ./
    - ../../ # ../ does not work properly (includes this twice)

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, env:stage, 'dev'}
  region: ${opt:region, env:region, 'us-east-1'}

custom:
  coreHooks:
    objects:
      - utils
      - cli
